@token=cdbab911d923bad9fe77a3893c41a8f81217760f
@localhost=http://127.0.0.1:8000



# KAYIT OL - KAYIT OL - KAYIT OL - KAYIT OL
### 
POST {{localhost}}/api/users/
Content-Type: application/json

{   
    "username": "deneme",
    "email": "deneme@deneme.com",
    "password": "123asd_123asd",
    "re_password": "123asd_123asd"
}


# GİRİŞ YAP - GİRİŞ YAP - GİRİŞ YAP - GİRİŞ YAP
### 
POST {{localhost}}/api/token/login
Content-Type: application/json

{   
    "email": "deneme@deneme.com",
    "password": "123asd_123asd"
}

# TOKEN ÇALIŞIYOR MU KONTROL ETME FONKSİYONU
### 
GET {{localhost}}/api/authDeneme
Authorization: Token {{token}}


# YOLCU OLUŞTUR - YOLCU OLUŞTUR - YOLCU OLUŞTUR
###
POST {{localhost}}/api/createPassenger/
Authorization: token {{token}}
Content-Type: application/json

{   
    "name":"yolcu1",
    "email": "yolcu1@yolcu1.com",
    "status": "1"
}

# GEZİ OLUŞTUR - GEZİ OLUŞTUR - GEZİ OLUŞTUR
###
POST {{localhost}}/api/createTrip/
Authorization: token {{token}}
Content-Type: application/json

{   
    "passenger":1,
    "totalDistance": "1 km",
    "startTime": "15.30",
    "status": "1"
}



# TÜM GEZİLER - TÜM GEZİLER - TÜM GEZİLER
### 
GET {{localhost}}/api/allTrips/
Authorization: token {{token}}

# TÜM YOLCULAR - TÜM YOLCULAR - TÜM YOLCULAR
### 
GET {{localhost}}/api/allPassengers/
Authorization: token {{token}}



# TEK YOLCU - TEK YOLCU - TEK YOLCU - TEK YOLCU 
### 
GET {{localhost}}/api/passenger/1
Authorization: token {{token}}


# TEK GEZİ - TEK GEZİ - TEK GEZİ - TEK GEZİ 
### 
GET {{localhost}}/api/trip/1
Authorization: token {{token}}




# Passenger Güncelle - Passenger Güncelle
### 
POST {{localhost}}/api/updatePassenger/1/
Authorization: token {{token}}
Content-Type: application/json

{   
    
    "name": "test",
    "email": "test",
    "status": "test"
}

# Trip Güncelle - Trip Güncelle - Trip Güncelle
### 
POST {{localhost}}/api/updateTrip/1/
Authorization: token {{token}}
Content-Type: application/json

{   
    "totalDistance": "145",
    "startTime": "27",
    "status": "1"
}

#YOLCU SİL-YOLCU SİL-YOLCU SİL-YOLCU SİL-YOLCU SİL
### 
DELETE {{localhost}}/api/passenger/1/delete/
Authorization: token {{token}}

#GEZİ SİL- GEZİ SİL- GEZİ SİL- GEZİ SİL- GEZİ SİL- GEZİ SİL
### 
DELETE {{localhost}}/api/trip/1/delete/
Authorization: token {{token}}

###
GET {{localhost}}/api/sendmail/