# Generated by Django 3.2.13 on 2022-05-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
                ('trips', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_passenger',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('totalDistance', models.CharField(max_length=255)),
                ('startTime', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geziler', to='api.passenger')),
            ],
            options={
                'db_table': 'api_trip',
            },
        ),
    ]
