# Generated by Django 3.2.13 on 2022-05-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_passenger',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalDistance', models.CharField(max_length=255)),
                ('startTime', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geziler', to='api.passenger')),
            ],
            options={
                'db_table': 'api_trip',
            },
        ),
    ]
